### ISSUE TITLE
vdo fails to build with target EPEL7 | Error: No Package found for python3, python3-devel

### ISSUE THREAD

**Issue by andreamtp** [dm-vdo/vdo#18]
When building vdo-6.2.1.48 with target EPEL7, the build fails with the following error:

```Getting requirements for vdo-6.2.1.48-1.el7.src
 --> 7:device-mapper-event-devel-1.02.149-10.el7_6.7.x86_64
 --> Already installed : gcc-4.8.5-36.el7_6.2.x86_64
 --> libuuid-devel-2.23.2-59.el7_6.1.x86_64
 --> Already installed : 1:make-3.82-23.el7.x86_64
 --> Already installed : systemd-219-62.el7_6.6.x86_64
 --> 1:valgrind-devel-3.13.0-13.el7.x86_64
 --> zlib-devel-1.2.7-18.el7.x86_64
Error: No Package found for python3
Error: No Package found for python3-devel


Traceback (most recent call last):
  File "/usr/bin/copr-rpmbuild", line 158, in main
    action(args, config)
  File "/usr/bin/copr-rpmbuild", line 288, in build_rpm
    builder.run()
  File "/usr/lib/python3.6/site-packages/copr_rpmbuild/builders/mock.py", line 40, in run
    self.produce_rpm(srpm, configdir, self.resultdir)
  File "/usr/lib/python3.6/site-packages/copr_rpmbuild/builders/mock.py", line 124, in produce_rpm
    raise RuntimeError("Build failed")
RuntimeError: Build failed```

**Comment by rhawalsh** [comment]
I am closing this issue, because the code in the 6.2.x.x branches is intended for an EL8 implementation, which will have the python3 packages available.  The 6.1.x.x branches should work on EL7 without modification.  We have updated the [front page](https://github.com/dm-vdo/vdo#releases) to reflect this fact.

Please comment if you have any additional questions.
